### ISSUE TITLE
Kalendar + Firebase database

### ISSUE THREAD

**Issue by twillstudio** [altinselimi/kalendar#1]
Hi everyone,

Ive 2 issues using this module with my firebase database. 

First, the div "details-card" isn't being taken into account when im pulling appointments from my firebase database.  

As you can see on the screenshot, appointments are being display, but when i'm using the following code in order to control what's inside the appointments blue rectangles, nothing is being display. 

<img width="1440" alt="capture d ecran 2018-08-20 a 12 19 41" src="https://user-images.githubusercontent.com/36391774/44373177-3c618180-a52b-11e8-8b72-22c0e3f1641e.png">

```
<div id='slot' slot="details-card" slot-scope="{appointment_props}">
            {{appointment_props.start_value.value | moment("add", "8 hours","hh:mm a")}} to 
             {{appointment_props.end_value.value | moment("add", "8 hours","hh:mm a")}}
 </div>
```

My second issue is that i want to be able to update or remove appointments when user clicks on them. It is related to the first issue obviously but its also related to the css of kalendar which indicated a "pointer-event:none" on the details-card. 

Thanks very much in advance.

**Comment by altinselimi** [comment]
Can you do this and let me know what it prints out
```
<div slot="details-card" slot-scope="{appointment_props}">
            {{appointment_props}}
 </div>
```

**Comment by altinselimi** [comment]
@twillstudio did you solve this, or you still encountering this problem ?

**Comment by twillstudio** [comment]
Hi Altin, If i write your code it displays as it is on my screenshot. Actually if i delete the div <div slot="details-card" slot-scope="{appointment_props}">, it still displays as it is on my screenshot. So no I didnt manage to solve it yet. 

Thanks in advance.

**Comment by altinselimi** [comment]
@twillstudio can you provide a little bit more information such as:
Browser version, Operating system and if there is any error in the console ?

**Comment by altinselimi** [comment]
@twillstudio closing this for the moment. Feel free to open it whenever you can replicate it on codepen or have more information to provide.
