### ISSUE TITLE
Weekly navigator is 1 day wrong

### ISSUE THREAD

**Issue by xlcrr** [altinselimi/kalendar#112]
This also effects the demo

Note that Monday and the first date in between the arrows are 1 day apart

![Screenshot 2022-06-10 at 17 47 40](https://user-images.githubusercontent.com/25985241/173113645-8d27ba93-ae7f-4ce4-8f4f-cb86ebd012f2.png)

Is there a way to overwrite these values?

**Comment by altinselimi** [comment]
@xlcrr thanks for the bug report. Currently there's no slot for populating week navigator.

**Comment by xlcrr** [comment]
Hi @altinselimi would it be possible to generate the correct date for the weekly navigator for all projects?
