### ISSUE TITLE
Feature. Event when date is changed

### ISSUE THREAD

**Issue by mserralta** [altinselimi/kalendar#122]
In order only needed events from API I think will be interesting to be able to notify when day is changed and app can get and update events from API to Kalendar.

I made some changes to me able to notify this. An array of visible days is sent with the event.

**Comment by altinselimi** [comment]
@mserralta hmm, good idea. I have made a comment in the PR. Will merge once that is done.

**Comment by enyosolutions** [comment]
This was merged but it seems it wasn't pushed on npm. Can you push it ?
![image](https://github.com/altinselimi/kalendar/assets/8433760/0510a8d1-e256-4bc2-9c2f-68660bd7eb3b)

**Comment by enyosolutions** [comment]
@altinselimi

**Comment by altinselimi** [comment]
@enyosolutions its published now, version 2.2.1. Have not tested it though so let me know if its working as expected.
