### ISSUE TITLE
different locale than en

### ISSUE THREAD

**Issue by pjadanowski** [altinselimi/kalendar#13]
is there a possibility to use other languages than English for displaying calendar?

**Comment by altinselimi** [comment]
Just merged #12 , that should probably meet your needs.

**Comment by pjadanowski** [comment]
I meant displaying days of week and months in another language e.g for german Monday would be Montag, Tuesday -> Dienstag etc. The same for months e.g January-> Januar etc

**Comment by altinselimi** [comment]
Yes, that is doable using slots that are introduced in #12 . Please check the [readme](
![image](https://user-images.githubusercontent.com/10469822/46072856-b36de380-c183-11e8-884f-bb7cb0c8e0f4.png)

**Comment by altinselimi** [comment]
Yes that is doable using slots that #12 introduces. Please check the [readme](https://github.com/altinselimi/kalendar#date-representations)

**Comment by pjadanowski** [comment]
can you show a short example because it seems to not take an effect

**Comment by altinselimi** [comment]
Oops, forgot to publish. Please run `npm install kalendar-vue@latest` and check again, it should work now.
