### ISSUE TITLE
Disabling hours

### ISSUE THREAD

**Issue by antooa** [altinselimi/kalendar#14]
Hello, how can I disable hours in the table? I just want to customize kalendar so I can assign some appointments for a whole day omitting hours. Thank you!

**Comment by altinselimi** [comment]
That is not supported currently. But, you can get around it doing the following:
In the completeAppointment method (find it in the docs), change the *from* and *to* field hour values to 00:00 and 24:00 respectively. Whatever user clicks will create an all-day event.

**Comment by antooa** [comment]
Sorry, I didn't get where to insert completeAppointment method. Into the 'export defaults'? Also, could you explain more about 'from' and 'to'? What do I have to change there and to what? I tried to put there "00:00" and "24:00" but nothing changed.

Also I don't understand how I can change height. It works only if I hardcode 'max-height' in <ul>hours . I tried wraping into the <div> but it also didn't worked for me.
Looking forward to hearing for you!

**Comment by altinselimi** [comment]
You must completely read the readme (line by line) and then get back here and take a look at my message again. If you still don't understand please let me know.
