### ISSUE TITLE
Import CSS throws not found error

### ISSUE THREAD

**Issue by satvikpendem** [altinselimi/kalendar#15]
When doing this step,
`import 'kalendar-vue/dist/KalendarVue.css';`

I get the error
`Module not found: Error: Can't resolve 'kalendar-vue/dist/kalendar-vue.css' in '/home/projectname/projectname/components'`

Is there another way to import them, or should I just download the CSS?

Also, when using `	<kalendar :configuration="calendar_settings" :appointments="appointments"/>`, is this all you need in the HTML part to make it render the calendar, or do you have to provide the full scoped slots stuff too?

Thanks.

**Comment by altinselimi** [comment]
Can you try running `npm install -S kalendar-vue@latest` and let me know what happens ?

You can totally render the calendar with only that, but its recommended that you make use of slots to display the data you need, and add the forms you need for user to add the appointments.

**Comment by satvikpendem** [comment]
I see, it's KalendarVue.css but on your website it's kalendar-vue.css. Now I'm getting an error about registering components, about an unknown custom element, but I included them in the App.vue file
```javascript
<template>
  <div id="app">
    <HelloWorld msg="Welcome to Your Vue.js App"/>
  </div>
</template>

<script>
import HelloWorld from './components/HelloWorld.vue'
import Kalendar from 'kalendar-vue';
import 'kalendar-vue/dist/KalendarVue.css';

export default {
  name: 'app',
  components: {
    HelloWorld,
    Kalendar
  }
}
</script>

<style>
#app {
  font-family: 'Avenir', Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}
</style>

**Comment by altinselimi** [comment]
Your code looks good, I can't really help you further as I do not know about other components. You can check out the [Codepen] example for more info.
