### ISSUE TITLE
Crash when creating event until end of day

### ISSUE THREAD

**Issue by igormp** [altinselimi/kalendar#16]
When trying to add an event that lasts until the end of the day (23:59:59), the whole thing just crashes. This is reproducible even in the demo (as seen bellow).

![mygif](https://user-images.githubusercontent.com/5247904/46555393-82935a00-c8b9-11e8-9ea2-de3cd0570e42.gif)

**Comment by altinselimi** [comment]
I’ll be checking this tomorrow. Thanks for noticing.

**Comment by ThiagoAugustoSM** [comment]
Did you solve this issue on the latest commit? @altinselimi

**Comment by altinselimi** [comment]
@ThiagoAugustoSM @igormp I'm happy to announce that this bug has been fixed on version 0.2.7. Please test it and let me know if you encounter any problem ! 🎉

**Comment by ThiagoAugustoSM** [comment]
Hey @altinselimi that's nice to hear! but i'm trying to use it, but it keeps not showing up the event. I just need to update the package in my package.json file, right? But it doesn't give an error anymore.

And also it keeps console.logging the values of the start and end date of what is being choose.

![screenshot](https://user-images.githubusercontent.com/19818077/47305638-7c62e480-d600-11e8-9152-4d9e4a29a046.png)

**Comment by altinselimi** [comment]
Yeah the console log part is not good, should be fixed in the next minor version I push, but as far as the event popping right, its working just fine in codepen and the demo web itself. Maybe you can try to replicate it in the codepen example ?

**Comment by altinselimi** [comment]
@igormp what browser are you using to replicate that ? I can't replicate it on codepen or live website. Can you also make sure you have cleared the cache ?

**Comment by altinselimi** [comment]
@ThiagoAugustoSM you should not touch your package.json, you should run `npm install kalendar-vue@latest -S` instead. That will take care of updating the package.json file.

**Comment by igormp** [comment]
> @igormp what browser are you using to replicate that ?

Managed to replicate that on the live website and codepen with both Chrome 69.0.3497.100 and Firefox 62.0.3

>Can you also make sure you have cleared the cache ?

Yes.

**Comment by altinselimi** [comment]
@igormp is it by any chance a Windows OS ? If so, you guys will have to wait two weeks till my ssd arrives so I can start testing :/

**Comment by igormp** [comment]
>is it by any chance a Windows OS ?

Nope, sorry for the misleading mouse cursor lol

**Comment by ThiagoAugustoSM** [comment]
@altinselimi i have already run the _npm install kalendar-vue@latest -S_ and it still doesn't work. I'm using windows 10, and i have tested on Chrome Version 69.0.3497.100 and Firefox version Versão 62.0.3

**Comment by altinselimi** [comment]
@ThiagoAugustoSM so you're having the same problem (not being able to select the last hour of the day), correct ?

**Comment by altinselimi** [comment]
This is fixed in latest version.
