### ISSUE TITLE
Week Navigator shows same date for start and end dates

### ISSUE THREAD

**Issue by andrewhl** [altinselimi/kalendar#18]
If you look at your [codepen example](https://codepen.io/altinselimi/pen/PdPLBZ), the start and end date in the week navigator is the same. I'm using that code as my starting point, and I'm not sure how to fix this.

**Comment by andrewhl** [comment]
Figured it out. You need to set the `template` slots for "first-date" and "last-date":

```javascript
    <!-- Date formatting -->
    <template slot="first-date" 
              slot-scope="{ date }">
      <!-- Displays first date in week navigation header -->
      {{ date | normalizeDate('MMM D') }}
    </template>
    <template slot="last-date" 
              slot-scope="{ date }">
      <!-- Displays last date in week navigation header -->
      {{ date | normalizeDate('MMM D, YYYY') }}
    </template>
```

You might want to indicate in the docs that `normalizeDate` can be implemented like so:

```javascript
  normalizeDate(date, dateFormat) {
    return format(date, dateFormat);
  }
```

And that `format` (which is also used elsewhere in your sample code without definition) comes from the `date-fns` library.

```javascript
import { format } from "date-fns";
```

**Comment by altinselimi** [comment]
This is fixed in the new version. Check out the new options in the readme of the library.
