### ISSUE TITLE
Disable event creation (i.e., read-only mode)

### ISSUE THREAD

**Issue by andrewhl** [altinselimi/kalendar#19]
Is it possible to have a read-only mode where event creation is disabled?

**Comment by altinselimi** [comment]
Yeah I will add this feature. At the moment just add a pointer-events:none on the wrapper.

**Comment by andrewhl** [comment]
That won't help me, because I want users to be able to click on and view events, without creating new ones. Admin users create events, other users sign up for them. That's the kind of behaviour I want to be able to support. Is that possible?

**Comment by altinselimi** [comment]
@andrewhl this is added in the latest build. You can find it as a field (*read_only*) in configuration object. Make sure you have the latest version of kalendar installed running `npm install kalendar-vue -S`
