### ISSUE TITLE
crypto.getRandomValues doesnt work on IE11

### ISSUE THREAD

**Issue by ItsRaWithTheH** [altinselimi/kalendar#2]
For IE11
the use of crypto as a global variable doesnt work on IE11 as crypto exists not as window.crypto but as window.msCrypto.

this can be fixed by adding `const crypto = window.crypto || window.msCrypto;` to kalendar-container and kalendar-cell.

Note, that if later adding type definitions or for users using typescript, the msCrypto would have to be added
```
declare global {
  interface Window{
    msCrypto: Crypto;
  }
}
```

Other options could be using non mscrypto polyfills such as https://github.com/gaswelder/window-crypto

**Comment by altinselimi** [comment]
Great catch. Can you make a PR for that ?

I'd rather not use a polyfill, as I would prefer the size of this component to be as small as possible. I'm actually planning to remove date-fns from dependencies too. In an ideal world, this component should only require `portal-vue` and `vue`.
