### ISSUE TITLE
Overlapping events

### ISSUE THREAD

**Issue by nidkil** [altinselimi/kalendar#22]
Hi Altin,

Excellent component! Really impressed.

I would like to make an enhancement and need your guidance where to start. The current implementation does not position events correctly if they overlap. They are positioned directly over each other. It would be if they would be positioned next to each other. In other words, that there width would be halved. If you would like to test this you can add the following events to the codepen you provide.

``` js
  {
    from: "Tue Nov 05 2018 01:00:00",
    to: "Tue Nov 05 2018 03:00:00",
    date: "2018-11-05",
    data: {
      title: "My Birthday",
      description: "Lorem ipsum dolor sit amet."
    }
  },
  {
    from: "Tue Nov 05 2018 02:00:00",
    to: "Tue Nov 05 2018 04:00:00",
    date: "2018-11-05",
    data: {
      title: "My Birthday",
      description: "Lorem ipsum dolor sit amet."
    }
  }
```

To better see the result switch to day view.

An additional problem I have noticed that it is not possible to create an overlapping event. The schedule is not clickable.

Regards, nidkil

**Comment by altinselimi** [comment]
Hey Stephen,
This is also a feature request. The groundwork is not yet there for overlapping events unfortunately. 
There will be another version released before christmas that will be a rewrite from scratch, and then shortly after (a week or so) will be another version which will have features you have requested.

Thanks !

**Comment by nidkil** [comment]
A complete rewrite? Sounds interesting. Do you need help?

**Comment by croossin** [comment]
@altinselimi Any updates on overlapping events?

**Comment by croossin** [comment]
@altinselimi Do you know when that release might happen?

**Comment by altinselimi** [comment]
@croossin @nidkil The rewrite is mostly done. Overlapping events is finally supported. Couple other requested features will be supported too. You can check it out v2 branch anytime you wish.

Not ready for public use yet though. I think it is fair to assume that it will happen sometimes next week.
