### ISSUE TITLE
Change period shown in day view

### ISSUE THREAD

**Issue by nidkil** [altinselimi/kalendar#24]
Hi Altin,

I would like to make a change to the day view that it is possible to limit the period of the day that is displayed. Now it displays the full day. I would like to limit it to a specific period, i.e. business hours (8:00-17:00).

Can you please provide me with guidance how to best approach this change?

Regards, Stephen

**Comment by altinselimi** [comment]
Hey Stephen, this is a feature that is going to be implemented soon enough. 
A possible workaround is to use css to hide the hours you don't want to show using the `nth-child` selector.
Example: 
```
// hide elements before the 4th child.
ul>li:nth-child(-n+4) {
    display:none;
}
// hide elements after the 10th child.
ul>li:nth-child(n+10) {
    display:none;
}

**Comment by nidkil** [comment]
Cool trick. I forked and changed your Codepen to demonstrate this (https://codepen.io/nidkil/pen/JeYYGr). Thx.

**Comment by nidkil** [comment]
Just noticed that the trick doesn't do the trick :-(

The bottom half of the schedule is not clickable, so it is not possible to add events. Any suggestions how I could get this to work?

**Comment by altinselimi** [comment]
@nidkil here you go https://codepen.io/altinselimi/pen/OayGdW

**Comment by nidkil** [comment]
Hi Altin, thx for the fix. It seems pretty sraight forward...

I have update my version to handle a 30 minute split as your update uses the 20 minute split, which causes the events to disapper. However I run into the same problem that the last cells are not clickable. I probably do not understand your comments correctly. I have updated your comments to reflect my understanding. Could you please double check what I am doing wrong? Thx.

https://codepen.io/nidkil/pen/JeYYGr

**Comment by mathieutu** [comment]
For information, this tricks **doesn't work at all**.

Even in the codepen, you can see that the now bar isn't set properly, and the hours of event are not ok.

Let us hope that the next version will be release soon (as "before end of year holidays" is past now for 1 month).

**Comment by altinselimi** [comment]
@mathieutu that is true, but the new version is definitely coming soon. My open source contributing time is always dependent on my work schedule, and unfortunately its been a tight one the past couple months.

**Comment by mathieutu** [comment]
@altinselimi Yeah of course, it's the same for all of us, but thanks for your answer, glad to read that!
