### ISSUE TITLE
Event time not positioned correctly

### ISSUE THREAD

**Issue by nidkil** [altinselimi/kalendar#25]
Hi Altin,

I have noticed that the event time is not positioned correctly. It falls outside the event area. You can test this with the codepen you provide using the following event.

```
  {
    from: "Tue Nov 05 2018 02:00:00",
    to: "Tue Nov 05 2018 04:00:00",
    date: "2018-11-05",
    data: {
      title: "My Birthday",
      description: "Lorem ipsum dolor sit amet."
    }
  }
```

The fix is pretty straight forward, changing the `.existing-event .time` from `12px` to `50px`. See below.

```
.existing-event .time {
    right: 50px;
}
```

Regards, nidkil

**Comment by altinselimi** [comment]
Should be fixed in the last version. Do reopen if you manage to reproduce it.
