### ISSUE TITLE
A new view type?

### ISSUE THREAD

**Issue by mesaglam** [altinselimi/kalendar#27]
Hi, do you have any plan to add Year View?
Thanks for all...

**Comment by altinselimi** [comment]
Not in the plan currently.
Main idea behind this library is providing the user with an intuitive way of creating events. 
You will always have the updated events array in your parent component.
That should make it possible for anyone to create a year-view for their application.

To put it more simply, it is very easily achievable, but I can't take more on my plate at the moment.
The new version of **Kalendar** is coming out soon, so keep out an eye for that. 
PR-s are welcome too :)
