### ISSUE TITLE
Mobile view?

### ISSUE THREAD

**Issue by disjfa** [altinselimi/kalendar#30]
Awesome component.

But i found a mobile view, checking on some mobile app agent. If we check the mobile views of the day there is no reason to check things like that. Maybe a media query to check the width of the browser. But i would prefer not to check those, Phones and tablets are wider than most modern desktops when checking.
https://www.w3schools.com/howto/howto_js_media_queries.asp

I just remove the media is mobile check in the element and everything worked better, maybe a touch drag in sync with the mouse down check to add.

When you add a overflow hidden on the `.day-indicator` class it still fits as it should :)

```
.day-indicator {
    padding-left: 5px;
    overflow: hidden;
    @media only screen and (min-width: 600px) {
        padding-left: 16px;
     }
}
```

Also would like to help. Don't know what the status is of the new developments. But if you know, please let us know here. Would like a nice standalone calendar for vue 👍

**Comment by altinselimi** [comment]
Hey @disjfa it would be great to have the touch events implemented but I'm not yet sure how we could go ahead with that. The v2 is merged to master and it should be fairly easy to start the server and development environment.

**Comment by disjfa** [comment]
It is not the touch events that you should worry about. The selector is already working a bit i see. The touch/drag for mobile you should skip because you cannot scroll when you want. The only problem i see now is a double creation of appointments that is happening now.

Base this is making the base work. Maybe i will see what happens soon to check some things.
