### ISSUE TITLE
"TypeError: from.getHours is not a function"

### ISSUE THREAD

**Issue by mgarcia96** [altinselimi/kalendar#33]
![image](https://user-images.githubusercontent.com/6561770/55808713-ed318680-5ae4-11e9-81cb-4afcac0821a6.png)

I don't know why it's crashing all time!

```
app.js:8368 [Vue warn]: Error in callback for watcher "appointments": "TypeError: from.getHours is not a function"

found in

---> <Kalendar> at kalendar-container.vue
```

**Comment by odelmas** [comment]
this was already aswered in issue 23 https://github.com/altinselimi/kalendar/issues/23

**Comment by altinselimi** [comment]
This should not happen in the new version as we deprecated the split_value option. Any time provided should be fine now.
