### ISSUE TITLE
Add start_hour/end_hour support

### ISSUE THREAD

**Issue by liudonghua123** [altinselimi/kalendar#35]
The day view is always from 0 a.m. to 11 p.m. which is not always convenience, because we merely add event in the very early morning or too late in the night.
So I add start_hour/end_hour support to customize this behavior like the following snapshot.

![image](https://user-images.githubusercontent.com/2276718/56865926-26835500-6a06-11e9-807d-61f254689fc5.png)

**Comment by liudonghua123** [comment]
You can quick try it with `npm i -S liudonghua123/kalendar#add_start_end_hour_support_build`, and then settings like below.
```
......
      calendar_settings: {
        style: 'material_design',
        view_type: 'Month',
        split_value: 10,
        cell_height: 15,
        scrollToNow: false,
        current_day: new Date(),
        military_time: false,
        read_only: false,
        start_hour: 8,
        end_hour: 17,
      },
......
```

**Comment by altinselimi** [comment]
@liudonghua123 this was added in v2. Do check it out at kalendar.altinselimi.com.

**Comment by liudonghua123** [comment]
@altinselimi, Thanks, 😃
