### ISSUE TITLE
Set start-date

### ISSUE THREAD

**Issue by JapSeyz** [altinselimi/kalendar#38]
Hi, I am unsure whether or not this is possible yet, but something like the ability to always have today's date as the left-most date and only see forwards in the calendar.

Cheers

**Comment by altinselimi** [comment]
Hey @JapSeyz , nice idea. 
This shouldn't be hard to implement. I am already doing something similar for hide_days and hide_dates. Check out `./src/components/kalendar/workers/worker.js` line 33 and see if you can work something out.

**Comment by jesusLM94** [comment]
Is this feature implemented yet? I saw it in the demo and there is a feature to hide days and set a start/end date.

https://kalendar.altinselimi.com/#getting-started

**Comment by jesusLM94** [comment]
Hello there, @altinselimi. Thanks for your amazing work, I really like Kalendar. Could you please build the project and publish a new version? 🙏

**Comment by altinselimi** [comment]
Hi @jesusLM94,
Thank you for your kind workds. I have completed implementation of the library but I am having problems with publishing it since web workers are not being bundled inline. Follow this issue to be updated:
webpack-contrib/worker-loader#212

**Comment by altinselimi** [comment]
@jesusLM94 @JapSeyz The new version addresses this issue and should now work as expected :)
