### ISSUE TITLE
Disable selection on a published event

### ISSUE THREAD

**Issue by mgarcia96** [altinselimi/kalendar#43]
Hello! I want to put just one item every hour! How can I disable that, because now, I can select and save items at the same hour

![image](https://user-images.githubusercontent.com/6561770/62474223-b3c30c00-b7a2-11e9-8c07-d139dfb048be.png)

**Comment by AnellyDev** [comment]
My quick-fix suggestion would be to intercept this in the creation function
( `completeAppointment` in the readme) but I'm no expert.

**Comment by altinselimi** [comment]
@mgarcia96  In the configuration object there is a field called `overlap`. Send that as false and it will prevent creating events in the same timeframe !

**Comment by altinselimi** [comment]
Btw @mgarcia96 is the plugin working on your end ? I am having problem using v2 since the web worker is being required incorrectly ?

**Comment by mgarcia96** [comment]
> Btw @mgarcia96 is the plugin working on your end ? I am having problem using v2 since the web worker is being required incorrectly ?

I don't try it yet! Thanks for the info!!
