### ISSUE TITLE
Remove Kalendar hours time and conflict with boostrap.css (v4.2)

### ISSUE THREAD

**Issue by rd1571** [altinselimi/kalendar#44]
1. Is there a way that I could remove the hours time and just display 1 row for adding event?

2. There is conflict with my bootstrap v4.2 and kalendar.css ?

![image](https://user-images.githubusercontent.com/11959780/62505925-24b10500-b831-11e9-881d-7a39dd91a543.png)

**Comment by altinselimi** [comment]
@rd1571 
1. I don't really understand the question. If you remove the hours how would the user create the event ?
2. Can you create a reproducible jsfiddle or something ?

**Comment by rd1571** [comment]
@altinselimi  I am creating 1 event per day.

**Comment by altinselimi** [comment]
@rd1571 you can use the new hide_days option to hide days that you don't need.
