### ISSUE TITLE
when I place the component in one of my nuxt.js views I get the following error (Cannot set property 'getEvents' of undefined)

### ISSUE THREAD

**Issue by jmuc-msm** [altinselimi/kalendar#45]
<img width="1536" alt="Captura de Pantalla 2019-08-16 a la(s) 10 33 12 a  m" src="https://user-images.githubusercontent.com/20538818/63175253-a531eb80-c011-11e9-9874-bf4011c0680b.png">
<img width="959" alt="Captura de Pantalla 2019-08-16 a la(s) 10 36 54 a  m" src="https://user-images.githubusercontent.com/20538818/63175370-dc080180-c011-11e9-9e58-6c5df85ad3ab.png">
<img width="370" alt="Captura de Pantalla 2019-08-16 a la(s) 10 37 20 a  m" src="https://user-images.githubusercontent.com/20538818/63175369-dad6d480-c011-11e9-94ab-087998c38d98.png">

**Comment by mgarcia96** [comment]
Same here, you solved that?

**Comment by altinselimi** [comment]
This is an issue with worker-loader. Until I solve it you should copy the kalendar component from the repo into your /src/components folder.

**Comment by altinselimi** [comment]
@mgarcia96 @jmuc-msm install the latest version of the library. It should work now.
