### ISSUE TITLE
please check this error, thx

### ISSUE THREAD

**Issue by 2535049762** [altinselimi/kalendar#47]
![image](https://user-images.githubusercontent.com/15008282/67285981-25da0000-f50b-11e9-9a70-6a1dcfdc9ad5.png)
![image](https://user-images.githubusercontent.com/15008282/67286021-37230c80-f50b-11e9-9eba-cee18adbd540.png)
![image](https://user-images.githubusercontent.com/15008282/67286046-41dda180-f50b-11e9-8b71-ff6cc1ac39a9.png)

**Comment by bilalceyylan** [comment]
I'm getting the same error

**Comment by yummyo** [comment]
![image](https://user-images.githubusercontent.com/29514211/75439533-efb6fc00-5994-11ea-80eb-386eca76c648.png)
在main.js 中添加图中一行代码。即可

**Comment by altinselimi** [comment]
@yummyo @bilalceyylan @2535049762 install the latest version of the library. It should work directly now.
