### ISSUE TITLE
KalendarVue.common.0.worker.js 404 (Not Found)

### ISSUE THREAD

**Issue by mgarcia96** [altinselimi/kalendar#49]
What's this? Is a new project with sample data...

**Comment by yummyo** [comment]
我在我的项目中也碰到了这个问题，有什么办法解决吗？

**Comment by altinselimi** [comment]
@mgarcia96 @yummyo its an issue with bundler and publishing a library that uses web workers. Currently the only workaround is to clone the project and use the `./components/kalendar` inside your project. Sorry, but haven't had much luck trying to find a solution :/
