### ISSUE TITLE
How to do new events Hourly?

### ISSUE THREAD

**Issue by mgarcia96** [altinselimi/kalendar#50]
Hey, when you select the hours for doing an event, you can choose with 10 min range, what if I only want hourly or 30 minutes rang?

**Comment by mgarcia96** [comment]
No news?

**Comment by altinselimi** [comment]
No, this is a feature request so it may take a bit longer. 
Also, currently I'm focused on fixing the web worker issue which is preventing the use of this library straight from NPM.

**Comment by mgarcia96** [comment]
> No, this is a feature request so it may take a bit longer.
> Also, currently I'm focused on fixing the web worker issue which is preventing the use of this library straight from NPM.

Hm okay, and there is any quick fix that can I implement? Like change in some js 10 minutes for a 60 minutes manually

**Comment by altinselimi** [comment]
Unfortunately no, there's no quick fix. From the top of my head, you would have to introduce a config option for minimum_selection and use that in KalendarCell.vue to check whether the cell we are hovering on should be selected.

**Comment by mgarcia96** [comment]
> Unfortunately no, there's no quick fix. From the top of my head, you would have to introduce a config option for minimum_selection and use that in KalendarCell.vue to check whether the cell we are hovering on should be selected.

Hm, and where I can find the function that makes the selection?

**Comment by altinselimi** [comment]
kalendar-cell.vue in the methods

**Comment by mgarcia96** [comment]
@altinselimi can you provide more info? What I've to do?

**Comment by altinselimi** [comment]
Dig up the code there and let me know if you have any questions.
