### ISSUE TITLE
Events loaded via Ajax not showing

### ISSUE THREAD

**Issue by mgarcia96** [altinselimi/kalendar#51]
Hey, the events that has loaded via axios are not loading, the kalendar has the events but they are not showing. 

![image](https://user-images.githubusercontent.com/6561770/69484370-bec5a900-0e32-11ea-999e-ed0e327e9c47.png)

**Comment by altinselimi** [comment]
Can you provide a codesandbox or some code I could look at ?

**Comment by altinselimi** [comment]
Any case, try a this.$forceUpdate after the ajax is done. Closing this as inactive.

**Comment by pkerspe** [comment]
I have the same issue here, updating events array does not cause the calendar to update, also call to $forceUpdate() does not help.

Locking at the code what is done with the property value:
**kalendar-container.vue / line 273:**
```
this.kalendar_events = this.events.map(event => ({
            ...event,
            id: event.id || generateUUID(),
        }));
```
The array from the property seems to get cloned / mapped thus the reference is lost if I get it right.
Also no code to watch the property values seems to be in place in kalendar-container.vue

any hint on how to react to changes of the events-property and update the displayed events?

**Comment by pkerspe** [comment]
as a rather dirty workaround I forced re-rendering of the complete DOM Sub tree for the calendar, by removing it from the DOM, updating the events-array and then adding it back in.
Obviously this is not a solution you want to go with in production. Currently I do not see another way without modifying the kalendar Component itself.

Is there any example that shows how to add events by code and "inject" them into the kalendar component without re-rendering the whole component?
