### ISSUE TITLE
TypeError: Cannot read property 'distance' of null

### ISSUE THREAD

**Issue by magarrent** [altinselimi/kalendar#52]
Hey there, it appears when (Ex):

day_starts_at: 8
day_ends_at: 22

And the actual time is more than 22!

**Comment by altinselimi** [comment]
Can you create a reproducable codesandbox or jsfiddle link or something I could debug this on ? Also, update to latest version of the library, it should work directly now.

**Comment by Fusseldieb** [comment]
Also facing this issue. If the time pointer is less or more than the specified times, I get a distance error and the calendar doesn't get rendered anymore.

**Comment by altinselimi** [comment]
@Fusseldieb I don't understand that. Time pointer referencing to what ?

**Comment by altinselimi** [comment]
@Fusseldieb so if I understand correctly, you want to render calendar only from 8 to 22. But there are events that are earlier or later than 08/22... Is that correct ?

**Comment by Fusseldieb** [comment]
> @Fusseldieb so if I understand correctly, you want to render calendar only from 8 to 22. But there are events that are earlier or later than 08/22... Is that correct ?

If the **time** is earlier than 8 or later than 22, it breaks.

**Comment by altinselimi** [comment]
You should be able to reproduce this in a codepen or something so I could give this a proper analysis @Fusseldieb
