### ISSUE TITLE
Not able to add kalendar-vue dependency (dependencies were not found)

### ISSUE THREAD

**Issue by redoc123** [altinselimi/kalendar#6]
Created a new project cal with vue cli 3.0.0

> vue create cal
> npm install --save kalendar-vue

then in HelloWorld.vue added the following:

import { Kalendar } from 'kalendar-vue';
import 'kalendar-vue/dist/kalendar-vue.css';

It gave me the following error:

 

> ERROR  Failed to compile with 2 errors                                                                                                                                      08:35:51
> 
> These dependencies were not found:
> 
> * kalendar-vue in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options!./src/components/HelloWorld.vue?vue&type=script&lang=js&
> * kalendar-vue/dist/kalendar-vue.css in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options!./src/components/HelloWorld.vue?vue&type=script&lang=js&
> 
> To install them, you can run: npm install --save kalendar-vue kalendar-vue/dist/kalendar-vue.css

**Comment by altinselimi** [comment]
You need to change kalendar-vue.css to KalendarVue.css
Updated the naming but forgot to update it on the readme and changelogs.

**Comment by redoc123** [comment]
Thanks for quick response..

I already changed it but it still gives me the following error:

```
 ERROR  Failed to compile with 1 errors                                                                                                                                      13:56:33

This dependency was not found:

* kalendar-vue in ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options!./src/components/Calendar/index.vue?vue&type=script&lang=js&

To install it, you can run: npm install --save kalendar-vue
```

**Comment by altinselimi** [comment]
@redoc123 can you please run 
`npm install kalendar-vue@latest -S`
It should be working now. 
_This happened because I renamed the main script without building the bundle and then publishing to NPM._

**Comment by redoc123** [comment]
thanks a bunch..it works now

**Comment by nidkil** [comment]
> You need to change kalendar-vue.css to KalendarVue.css
> Updated the naming but forgot to update it on the readme and changelogs.

@altinselimi This works thx. The documentation is incorrect.
