### ISSUE TITLE
missing modules

### ISSUE THREAD

**Issue by danishfred** [altinselimi/kalendar#7]
I'm using vue as frontend with meteor and get this error after install npm i kalendar-vue -S:

"If you notice problems related to these missing modules, consider running:
  meteor npm install --save kalendar-vue"  over and over again

any suggestions ???

**Comment by altinselimi** [comment]
make sure you have version 0.2.2 installed, and then let me know if it displays that error again
`npm install kalendar-vue@latest -S`

**Comment by altinselimi** [comment]
`KalendarVue.css` is the correct filename. That is mentioned in the readme too.

Not sure how importing modules works in the current development environment you are sitting on, but I would suggest you try to import kalendar-vue module directly from this link:
`https://cdn.jsdelivr.net/npm/kalendar-vue@0.2.2/dist/KalendarVue.umd.min.js`
And the css from this one:
`https://cdn.jsdelivr.net/npm/kalendar-vue@0.2.2/dist/KalendarVue.min.css`

Can you share some more information about your build system, node version and OS ?

**Comment by ShaikAsif007** [comment]
> `KalendarVue.css` is the correct filename. That is mentioned in the readme too.
> 
> Not sure how importing modules works in the current development environment you are sitting on, but I would suggest you try to import kalendar-vue module directly from this link:
> `https://cdn.jsdelivr.net/npm/kalendar-vue@0.2.2/dist/KalendarVue.umd.min.js`
> And the css from this one:
> `https://cdn.jsdelivr.net/npm/kalendar-vue@0.2.2/dist/KalendarVue.min.css`
> 
> Can you share some more information about your build system, node version and OS ?

i used your cdn files as am not using node js or web package in my current project am not sure how to import the code it says 

vue.js:634 [Vue warn]: Unknown custom element: <kalendar> - did you register the component correctly?

when i load my index.html

**Comment by altinselimi** [comment]
@ShaikAsif007 0.2.2 is old version, try using the new version
