### ISSUE TITLE
Calendar is only render without  error between  day_starts_at and  day_ends_at values

### ISSUE THREAD

**Issue by leon-developer-br** [altinselimi/kalendar#73]
Hi, 

The Kalendar here is configured to permit event between 8 an 22 hours for example. If I try to render the Kalendar outside this window, I catch this error: 
```
[Vue warn]: Error in render: "TypeError: _vm.passedTime is null"
```

**Comment by altinselimi** [comment]
I am guessing these events are coming from another source ? If so, you should be able to `.filter` out these elements before assigning them to the Kalendar object.
