### ISSUE TITLE
Changing the cell height breaks the hour indicator

### ISSUE THREAD

**Issue by frentrop** [altinselimi/kalendar#75]
When changing the cell height, the hour indicator does not scale accordingly, resulting in an incorrect position of the indicator. This also affects the scrollToNow, as this function focusses on the hour indicator.  

Attached is a screenshot with this issue. At the time of the screenschot it is 14:25, while the hour indicator shows it's about 20:45. 

![image](https://user-images.githubusercontent.com/7302812/88799801-5724e200-d1a7-11ea-9cea-c05ac34bc95b.png)

**Comment by altinselimi** [comment]
Good catch !
