### ISSUE TITLE
Adding Colors to Events

### ISSUE THREAD

**Issue by DrJfrost** [altinselimi/kalendar#78]
I wanted to congratulate the great work this lib has and how good the slots were thought.

Also I would like to note that A nice feature would be the ability to add colors to the events, since having many events can be confusing, maybe 5 or 10 colors? just like Mystudylife Schedule looks :smile: I think it would add a lot of value to the library and would be easy to add like some css classes?

**Comment by altinselimi** [comment]
@DrJfrost that can be easily achieved with the scoped slots this library already offers ! But I don't think its worthy feature for this library. Im trying to keep it as simple as possible, as calendars are already very much complicated 🤪
