### ISSUE TITLE
click event

### ISSUE THREAD

**Issue by boardmain** [altinselimi/kalendar#8]
hi how to handle the click on the event ?( for editing or delete it ) i tried to add @click to details-card but it will not be fired

**Comment by altinselimi** [comment]
This is actually a bug, I will fix this and update here accordingly.

**Comment by altinselimi** [comment]
@boardmain just published a new version which should fix this error. Please run `npm install kalendar-vue@latest -S` and check it out.
I also implemented appointment deletion in the demo page [here](https://kalendar.netlify.com/)
The code is available in the src/components/demo/Hello.vue at *details-card* slot.
