### ISSUE TITLE
Unable to run kalendar

### ISSUE THREAD

**Issue by gitgkk** [altinselimi/kalendar#94]
Hi,

I cloned the source, installed packages but on executing 'npm run serve'
D:\workspace\vue\kalendar>npm run serve

> kalendar-vue@2.1.1 serve D:\workspace\vue\kalendar
> vue-cli-service serve src/serve-dev.js

 ERROR  Error: Cannot find module '@babel/compat-data/corejs3-shipped-proposals'
Require stack:
- D:\workspace\vue\kalendar\node_modules\@babel\preset-env\lib\polyfills\corejs3\usage-plugin.js
- D:\workspace\vue\kalendar\node_modules\@babel\preset-env\lib\index.js
- D:\workspace\vue\kalendar\node_modules\@babel\core\lib\config\files\plugins.js
- D:\workspace\vue\kalendar\node_modules\@babel\core\lib\config\files\index.js
- D:\workspace\vue\kalendar\node_modules\@babel\core\lib\index.js
- D:\workspace\vue\kalendar\node_modules\@vue\cli-plugin-babel\index.js
- D:\workspace\vue\kalendar\node_modules\@vue\cli-service\lib\Service.js
- D:\workspace\vue\kalendar\node_modules\@vue\cli-service\bin\vue-cli-service.js
Error: Cannot find module '@babel/compat-data/corejs3-shipped-proposals'
Require stack:
- D:\workspace\vue\kalendar\node_modules\@babel\preset-env\lib\polyfills\corejs3\usage-plugin.js
- D:\workspace\vue\kalendar\node_modules\@babel\preset-env\lib\index.js
- D:\workspace\vue\kalendar\node_modules\@babel\core\lib\config\files\plugins.js
- D:\workspace\vue\kalendar\node_modules\@babel\core\lib\config\files\index.js
- D:\workspace\vue\kalendar\node_modules\@babel\core\lib\index.js
- D:\workspace\vue\kalendar\node_modules\@vue\cli-plugin-babel\index.js
- D:\workspace\vue\kalendar\node_modules\@vue\cli-service\lib\Service.js
- D:\workspace\vue\kalendar\node_modules\@vue\cli-service\bin\vue-cli-service.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (D:\workspace\vue\kalendar\node_modules\@babel\preset-env\lib\polyfills\corejs3\usage-plugin.js:10:55)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! kalendar-vue@2.1.1 serve: `vue-cli-service serve src/serve-dev.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the kalendar-vue@2.1.1 serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Albert\AppData\Roaming\npm-cache\_logs\2021-06-13T09_28_07_308Z-debug.log

What is the problem? How to resolve?

Thanks,
Kashyap

**Comment by altinselimi** [comment]
I have no idea what this is, can you try making a replica of your problem on codesandbox ?

**Comment by franklin113** [comment]
I fixed this by updating babel in the config.json
`        "@babel/core": "^7.9.0",
        "@babel/preset-env": "^7.9.0",`

**Comment by altinselimi** [comment]
so we can consider this closed then. Thanks @franklin113 !
