### ISSUE TITLE
Time Zone issue and Some Appointments are missing after 12PM

### ISSUE THREAD

**Issue by umerdev228** [altinselimi/kalendar#97]
Hello,
Kalendar showing accurate time on codepen or other JS playground but wrong in project and some slots or appointments after 12:00pm are not showing
![Screenshot_1](https://user-images.githubusercontent.com/75834709/136144973-1efbddb0-051c-43bd-8500-575b1a98cb5f.png)
.

**Comment by altinselimi** [comment]
In other words, the library doesn't have issues with moment/moment-timezone. Its just that it requires a specific date format for displaying dates. And also outputs a specific format which you have to take into account when storing/updating dates.
